Added IDs to headings for anchor links
WordPress/Learn pull request #1880
Opened 2023-09-23 12:24 UTC by yuliyang

Lesson plan's pattern template has "Lesson Wrap Up" section at the end that anchor links to Exercises and Assessment.
Lots of lesson plan's anchor links are not working. Initially, the anchor links are `#Exercises` and `#Assessment`, so I made all heading's IDs capitalized as well. Let me know if I should change everything to lowercase.

Examples of headings have **lowercase** IDs but anchor link is **capitalized**:
https://learn.wordpress.org/lesson-plan/how-to-build-low-code-block-patterns/
https://learn.wordpress.org/lesson-plan/anonymizing-information-in-the-browser/

Example of no IDs in headings:
https://learn.wordpress.org/lesson-plan/how-to-add-and-remove-logo-and-site-icon-in-site-editor/#Assessment

2023-10-10 07:49 UTC, jonathanbossenger commented
I am adding this context from our dev-squad triage discussions, as well as from the [training team meeting on 10 October 2023](https://wordpress.slack.com/archives/C02RW657Q/p1696923660650259)

Generally, when implementing internal [anchor link fragments](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web#fragment) (where an HTML anchor tag links to the id attribute of another element on the same page instead of an external URL) the fragment uses lowercase, not sentence case. While this does not seem to be a requirement according to the HTML spec, it's not something commonly used, as most developers will use lowercase when defining id attributes of HTML elements.

However, the Tip box in the lesson plan saved pattern defines the links as sentence-case, but there are also some instances where it might be all lowercase. So while we're not sure that the case ultimately matters, we do think it should be formalized, documented, and then used accordingly across the site.

So this leaves us with a question, and a follow-up problem:

1. Should we stick to sentence case, or switch to all lowercase.
2. Whatever we decide, once implemented, we'll need to review both the lesson plan saved pattern, and any existing lesson plans, to ensure the links work as expected.

2023-10-10 07:58 UTC, jonathanbossenger commented
@Piyopiyo-Kitsune asked "From my end, I'm curious if this will still be an issue if we consolidate our content [like how the new information architecture for Learn proposes](https://make.wordpress.org/training/2023/09/26/looking-for-feedback-learn-website-information-architecture/) :thinking_face: (edited)" with a follow up that "I have a strong feeling that area could change with this restructuring."

If this is the case, then perhaps it just makes more sense to merge this PR as is, and update any broken lesson plans on a case by case basis.

2023-10-10 10:56 UTC, jonathanbossenger commented
I'm going to add that I think it's probably okay to merge this PR as is.

2023-10-12 07:16 UTC, jonathanbossenger approved these changes

2023-10-12 07:16 UTC, jonathanbossenger commented
@adamwoodnz could I ask you to review this, please? Everything looks okay from my end, but I'd prefer a second pair of eyes.

2023-10-12 07:18 UTC, jonathanbossenger commented
Closes #1919

2023-10-15 22:55 UTC, adamwoodnz commented
Thanks for working on this @yuliyang, nice work!

> Let me know if I should change everything to lowercase.

👍 Yes I think we should update this to be more inline with standard practice.

Given this is just a template it won't affect any existing lesson plans. They will need to be edited to match.

2023-10-15 22:55 UTC, adamwoodnz requested changes
See comment

2023-10-15 23:01 UTC, adamwoodnz commented on wp-content/themes/pub/wporg-learn-2020/patterns/00-en-lesson-plan.php
> +<p>There should be one assessment item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.</p>
❤️

2023-10-18 18:12 UTC, yuliyang commented
@adamwoodnz I updated all IDs to lowercase and also the anchor links.
I'm not sure how to deal with other languages' pattern template since I can't read them. Can we create a new issue and request for help?

2023-10-25 20:48 UTC, adamwoodnz approved these changes
LGTM 💯

2023-10-25 20:49 UTC, merged

2023-10-25 22:14 UTC, adamwoodnz commented
> Can we create a new issue and request for help?

[German issue](https://github.com/WordPress/Learn/issues/1952)