Add breadcrumbs to templates
WordPress/Learn pull request #2491
Opened 2024-06-03 16:27 UTC by renintw

Add breadcrumbs to the sites, except for Home and the Learning Pathway taxonomy. See [design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3199-20648&m=dev).

Closes #2442

I noticed in the design there's a `Learn WordPress` breadcrumb, which link does it link to? It appears to be redundant with 'Home'. @WordPress/meta-design 
![image](https://github.com/WordPress/Learn/assets/18050944/fb9b9ced-4754-4511-b814-a0655a8b4603)

## Screenshots

| post type | screenshot |
|-|-|
| **Home** | ![Screenshot 2024-06-04 at 00 17 08](https://github.com/WordPress/Learn/assets/18050944/17acb74b-29f0-4f32-9d52-813ebe3b7d66) |
| **Post** | ![Screenshot 2024-06-04 at 00 56 43](https://github.com/WordPress/Learn/assets/18050944/ba86ae51-f321-4e8c-9910-10bb4499937d) |
| **My Course** | ![Screenshot 2024-06-04 at 00 27 47](https://github.com/WordPress/Learn/assets/18050944/8af7b95e-0501-4f7b-a242-02165455d0ac) |
| **Online Workshops** | ![Screenshot 2024-06-04 at 00 27 23](https://github.com/WordPress/Learn/assets/18050944/97cd3b2a-531f-44c0-a0a1-eeb28179e9fb) |
| **Apply to Faciliate** | ![Screenshot 2024-06-04 at 00 27 30](https://github.com/WordPress/Learn/assets/18050944/699aa0a6-6b41-4535-b4ca-1fd211aedc3c) |
| **Grandchild Page** | ![Screenshot 2024-06-04 at 00 27 39](https://github.com/WordPress/Learn/assets/18050944/b6fa3343-d5f9-4e9d-957f-341e0b293fa5) |
| **Contribute** | ![Screenshot 2024-06-04 at 00 27 13](https://github.com/WordPress/Learn/assets/18050944/28d1ac24-ca8c-446b-a5f9-94b2af591de0) |
| **Lessons Archive** | ![Screenshot 2024-06-04 at 00 27 00](https://github.com/WordPress/Learn/assets/18050944/51bb4565-c8bb-4531-825e-d98ad3c8704c) |
| **Courses Archive** | ![Screenshot 2024-06-04 at 00 17 32](https://github.com/WordPress/Learn/assets/18050944/378a8a07-65cb-482c-bbc8-f3807777b439) |
| **Single Course** | ![Screenshot 2024-06-04 at 00 17 45](https://github.com/WordPress/Learn/assets/18050944/70562520-6e96-429b-a678-c2fcc75942ae) |
| **Learning Pathways** (got some issues rendering image here in the local env, but yeah this is the learning pathways) | ![Screenshot 2024-06-04 at 00 17 20](https://github.com/WordPress/Learn/assets/18050944/cd74fc92-d893-4a95-a5fd-74656128da57) |

2024-06-03 22:59 UTC, adamwoodnz commented
> **Learning Pathways** (got some issues rendering image here in the local env, but yeah this is the learning pathways)

Looks like this is actually the [section title](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php#L51). $content should be coming from this [function](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L153), seems like the reference is not working for you?

2024-06-03 23:03 UTC, adamwoodnz commented
Single lesson is showing the course name but not the lesson name

![Screenshot 2024-06-04 at 11 02 21 AM](https://github.com/WordPress/Learn/assets/1017872/a900b6e6-5816-4e6a-9324-668972e16488)

2024-06-03 23:12 UTC, adamwoodnz requested changes
Looking good! Apart from the second 'Learn WordPress' breadcrumb you've noted, the only other thing I've noticed is that the `/learning-pathways` page shouldn't have breadcrumbs

![Screenshot 2024-06-04 at 11 07 02 AM](https://github.com/WordPress/Learn/assets/1017872/7710f7ca-0575-4e84-a17b-095e8767e1e0)

2024-06-04 10:21 UTC, fcoveram commented
> I noticed in the design there's a Learn WordPress breadcrumb, which link does it link to? It appears to be redundant with 'Home'.

You are right @renintw. The "Learn WordPress" link should not be there, sorry for the confusion. The mockups were updated.

2024-06-04 18:13 UTC, renintw commented
> Looks like this is actually the [section title](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php#L51). $content should be coming from this [function](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L153), seems like the reference is not working for you?

Since I got all these error messages, those lines are currently commented out.
What are the steps to properly set up the learning pathway config? I reckon some settings need to be done in the wp-admin. And does it require to activate sensei pro to make the functions fully work?

![image](https://github.com/WordPress/Learn/assets/18050944/85be08aa-382c-49e9-9c59-e18b97e9124d)

```Notice: Trying to get property ‘term_id’ of non-object in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 11 Notice: Trying to get property ‘slug’ of non-object in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 12 Notice: Trying to get property ‘term_id’ of non-object in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 14 Notice: Trying to get property ‘term_id’ of non-object in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 15 Notice: Trying to get property ‘term_id’ of non-object in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 16 Notice: Undefined index: in /var/www/html/wp-content/themes/pub/wporg-learn-2024/functions.php on line 214```
```
Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 51
Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php on line 58```

2024-06-04 18:27 UTC, renintw commented
> the only other thing I've noticed is that the /learning-pathways page shouldn't have breadcrumbs

Missed that page, there are currently no CTAs that can link to this page right?

2024-06-04 19:37 UTC, renintw commented
> Single lesson is showing the course name but not the lesson name

| | screenshot |
|-|-|
| lesson not belong to any course | ![Screenshot 2024-06-05 at 04 11 57](https://github.com/WordPress/Learn/assets/18050944/939fe5cf-a00d-414c-a06d-2073db9056f1) |
| lesson belong to certain course | ![Screenshot 2024-06-05 at 04 34 14](https://github.com/WordPress/Learn/assets/18050944/bd9cd4b3-e86a-4ea4-85ae-b67a148d0a8e) |

2024-06-04 20:50 UTC, adamwoodnz commented
> > Single lesson is showing the course name but not the lesson name
> 
> A lesson that belongs to a course can be accessed from the lesson archive or from its associated course page. If accessed from the course page, the breadcrumbs shown in the screenshot below would make sense. However, if accessed from the lesson archive, the user might expect to be able to return to the lesson archive? Currently, I am providing a more consistent experience for users who enter a lesson from its associated course. What do you think? (I'm thinking if users want to go back to the lesson archive, they can simply use the back button. Moreover, when they click into a lesson and see that it belongs to a specific course, it can potentially encourage them to explore more content. It's still a bit inconsistent in a sense, though)
> 
> screenshot
> lesson not belonging to any course	![Screenshot 2024-06-05 at 04 11 57](https://private-user-images.githubusercontent.com/18050944/336585148-939fe5cf-a00d-414c-a06d-2073db9056f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzQxODYsIm5iZiI6MTcxNzUzMzg4NiwicGF0aCI6Ii8xODA1MDk0NC8zMzY1ODUxNDgtOTM5ZmU1Y2YtYTAwZC00MTRjLWEwNmQtMjA3M2RiOTA1NmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIwNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTRkNGFhN2M4NzUxODEyNDA3ZDIwMGIzMWI2N2Q3OTllNjViNzQ2ZDExNjIyM2M5ZmFjNTZhZTg0M2ZjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mi3HO0sejw2d0wEsafm7bRVjT2a85SnaTxnBMlMolk)
> lesson belonging to certain course	![Screenshot 2024-06-05 at 04 34 14](https://private-user-images.githubusercontent.com/18050944/336585159-bd9cd4b3-e86a-4ea4-85ae-b67a148d0a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzQxODYsIm5iZiI6MTcxNzUzMzg4NiwicGF0aCI6Ii8xODA1MDk0NC8zMzY1ODUxNTktYmQ5Y2Q0YjMtZTg2YS00ZWE0LTg1YWUtYjY3YTE0OGQwYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIwNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTExNDVhYmFjMGY3ZWI5NmEzZjU3MjA5MzQzZjIxOTJmOTRlMTlhYjJjYThmZmRhN2ZhZDAyN2RkNDM5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMx0OUGZWtR_1j7POcIDME2v8VYhivu30ydoJ1zySAU)

I think it would be quite unusual for a Lesson to not be part of a Course, so I think prioritising that structure makes sense. In the rare case when it is free standing, having the lesson archive as the parent makes sense to me.

2024-06-04 20:56 UTC, adamwoodnz commented
> > Looks like this is actually the [section title](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/patterns/taxonomy-learning-pathway-content.php#L51). $content should be coming from this [function](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L153), seems like the reference is not working for you?
> 
> Since I got all these error messages, those lines are currently commented out. What are the steps to properly set up the learning pathway config? I reckon some settings need to be done in the wp-admin. And does it require to activate sensei pro to make the functions fully work?

This isn't using any sensei pro features, just a custom taxonomy. Maybe you don't have the taxonomy set up with the expected slugs; there should be `developer`, `user`, `designer`, and `contributor`. You can edit the slugs at http://localhost:8888/wp-admin/edit-tags.php?taxonomy=learning-pathway&post_type=course

![Screenshot 2024-06-05 at 8 54 01 AM](https://github.com/WordPress/Learn/assets/1017872/2ddb3de2-4c80-4e19-8836-86976cb12a90)

I've added a taxonomy guard in this [PR](https://github.com/WordPress/Learn/pull/2497/files#diff-fcc6da726b6514b8daa65a2f21d8b0bc9f180068955339576ce3c9f9f492086f) but obviously needs more to check the term exists.

2024-06-05 00:10 UTC, adamwoodnz commented
Also just noticed there should be no breadcrumbs on the [Courses](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-44005&m=dev) or [Lessons](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42972&m=dev) archives, sorry I missed this, maybe the designs changed...

2024-06-05 01:59 UTC, adamwoodnz commented
And the empty breadcrumbs are still taking up space on the pages where we return early:

| Learning Pathways | Learning Pathway |
|--------|--------|
| ![Screenshot 2024-06-05 at 1 56 06 PM](https://github.com/WordPress/Learn/assets/1017872/41e23c0a-c889-4966-8c39-f8403c144ddd) | ![Screenshot 2024-06-05 at 1 55 17 PM](https://github.com/WordPress/Learn/assets/1017872/89d9c83b-ba8c-4563-9bc2-5ff45e8168b8) |

2024-06-05 05:28 UTC, renintw commented
> Also just noticed there should be no breadcrumbs on the [Courses](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-44005&m=dev) or [Lessons](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42972&m=dev) archives, sorry I missed this, maybe the designs changed...

Just to double confirm, are those pages supposed to not have breadcrumbs? @WordPress/meta-design Thanks.

2024-06-05 05:39 UTC, renintw commented
> I think it would be quite unusual for a Lesson to not be part of a Course, so I think prioritising that structure makes sense. In the rare case when it is free standing, having the lesson archive as the parent makes sense to me.

ah. I mean for lessons that are part of a Course, users can typically get into those lessons in two ways:
1. from a [course](https://learn.wordpress.org/test/course/beginner-wordpress-contributor/).
2. from the homepage or [lesson archive](https://learn.wordpress.org/test/lessons/).
the current breadcrumbs implementation makes the flow consistent for users entering a lesson through a course page. (they can see the previous paths, which include the course title and the course archive)
but it kind of isn't when users coming from the homepage or lesson archive. (I imagine users would expect to see the Learn archive as the previous path in the breadcrumbs)

2024-06-05 07:55 UTC, renintw commented
> Maybe you don't have the taxonomy set up with the expected slugs; there should be developer, user, designer, and contributor.

I had set these values from the beginning. I just added the missing contributor, but it's still the same.

2024-06-05 08:05 UTC, fcoveram commented
> > Also just noticed there should be no breadcrumbs on the [Courses](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-44005&m=dev) or [Lessons](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42972&m=dev) archives, sorry I missed this, maybe the designs changed...
>
> Just to double confirm, are those pages (archives) supposed to not have breadcrumbs?

Exactly. No breadcrumb on pages that are visible in the local nav. That includes Courses and Pages, and from [these screenshots](https://github.com/WordPress/Learn/pull/2491#issue-2331580217) I see it's also on My courses. It should be hidden on this page as well.

Regarding landing on the "Learning Pathway" page (as per [this comment](https://github.com/WordPress/Learn/pull/2491#issuecomment-2148152715)), it was intentionally not linked from the homepage and local nav. Adding an index page that does not provide more info for browsing content felt unnecessary.

2024-06-05 09:09 UTC, adamwoodnz commented
> > I think it would be quite unusual for a Lesson to not be part of a Course, so I think prioritising that structure makes sense. In the rare case when it is free standing, having the lesson archive as the parent makes sense to me.
> 
> ah. I mean for lessons that are part of a Course, users can typically get into those lessons in two ways:
> 
> 1. from a [course](https://learn.wordpress.org/test/course/beginner-wordpress-contributor/).
> 2. from the homepage or [lesson archive](https://learn.wordpress.org/test/lessons/).
> 
> The current breadcrumbs implementation makes the flow consistent for users entering a lesson through a course page. (they can see the previous paths, which include the course title and the course archive) but it kind of isn't when users coming from the homepage or lesson archive. (I imagine users would expect to see the Learn archive as the previous path in the breadcrumbs)

The breadcrumbs aren't supposed to reflect the browsing history though, [rather the information hierarchy](https://www.nngroup.com/articles/breadcrumbs/). That's what I expect, if I want to go back I can use browser history.

2024-06-05 09:11 UTC, adamwoodnz commented
> > Maybe you don't have the taxonomy set up with the expected slugs; there should be developer, user, designer, and contributor.
> 
> I had set these values from the beginning. I just added the missing contributor, but it's still the same.

Hmm I'm not sure what's going on then. It isn't an issue on staging or prod, so it seems likely it's local config. Happy to help debug if you like.

2024-06-05 17:42 UTC, renintw commented
The feedback mentioned above has already been addressed.

@fcoveram There are still some inconsistencies though. One of the reasons is that the local nav still seems incomplete on the sites.
I'd like to confirm a few things:

1. The local nav only goes up to the second level, right? 
Like Learn WordPress (First)。Courses (Second)
![image](https://github.com/WordPress/Learn/assets/18050944/39654149-b8b2-45a9-9770-cc1c408f7ec8)

2. Pages should not have breadcrumbs, but I see some [do](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3652-11746&m=dev) and some [don't](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-41452&m=dev) in the design.

3. If pages shouldn't have breadcrumbs, should a child or grandchild have them? I see it [does](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42281&m=dev) in the design. (How should the local nav work in this case?) 
![image](https://github.com/WordPress/Learn/assets/18050944/68b14815-16ea-4e2b-a5f6-c1699c4a97fc)

Does it make sense to summarize that the local navigation will display up to the second level, and breadcrumbs start to display from when it's the third level?
It looks like this is the case for the [developer pages](https://developer.wordpress.org/block-editor/) (although its local nav doesn't display the second level directly like this [design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-43157&m=dev) unless scrolled)

2024-06-06 07:45 UTC, adamwoodnz approved these changes
Code changes LGTM. You could ship this then iterate on the page things in a separate PR maybe.

2024-06-06 09:24 UTC, fcoveram commented
I think we're missing the part of how local nav and breadcrumb behave. IIRC, all discussion and decision happened in [wporg-mu-plugins#535](https://github.com/WordPress/wporg-mu-plugins/issues/535). Here are [the designs](https://www.figma.com/design/VO03eHjoYJrX1aLisReB8q/Simpler-navigation?node-id=1-2193&m=dev) that show different uses cases across the site, and the diagram below summarizes what's in the design file.

![Diagram of local nav behavior](https://github.com/WordPress/Learn/assets/895819/5eaf8cb2-2488-41e7-9868-15d93b587af6)

In this [screenshot](https://private-user-images.githubusercontent.com/18050944/336944623-39654149-b8b2-45a9-9770-cc1c408f7ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjU5MDEsIm5iZiI6MTcxNzY2NTYwMSwicGF0aCI6Ii8xODA1MDk0NC8zMzY5NDQ2MjMtMzk2NTQxNDktYjhiMi00NWE5LTk3NzAtY2MxYzQwOGY3ZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5MjAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNWVkMDQzNTgwYTE4NjQxM2E5MTY0OWZlYWJjMDk3ZGQ0ODUyYWZhMTBkMDFjYTMwYzY5NTk0MjM1NDEwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.erPtLD2iieuM-tDv1b_n7OXkWCA7hG1MnbseVrwZPI8), `Learn WordPress` is a link to self and `Course` is a label of the page where users are that show up when scrolling down. Take a look at the [accessibility page](https://wordpress.org/about/accessibility/).

2024-06-06 13:38 UTC, renintw commented
Thanks @fcoveram, that's very clear!
I'll move the tweaks of the local nav along with the breadcrumbs of pages into another [ticket](https://github.com/WordPress/Learn/issues/2511).

2024-06-06 13:43 UTC, merged