Add WordPress version to filters & display on Lesson Plans and Workshops
WordPress/Learn pull request #292
Opened 2021-12-16 22:10 UTC by ryelle

Fixes #289 — This adds the WP version to Lesson Plans and Workshops, and adds filtering on that value.

Display on lesson plan
<img width="999" alt="Screen Shot 2021-12-16 at 5 04 51 PM" src="https://user-images.githubusercontent.com/541093/146455971-1ff8245d-f83e-4c6c-baaa-5fa8825779f3.png">

Display on lesson plan list
<img width="693" alt="Screen Shot 2021-12-16 at 5 03 32 PM" src="https://user-images.githubusercontent.com/541093/146456071-57416904-492e-4561-9662-3728fa416314.png">

Display on workshop
<img width="349" alt="Screen Shot 2021-12-16 at 5 04 20 PM" src="https://user-images.githubusercontent.com/541093/146456003-40ac1d48-63c0-4b15-aaaa-35cf2f04104f.png">

Filter in lesson plan sidebar
<img width="323" alt="Screen Shot 2021-12-16 at 5 03 54 PM" src="https://user-images.githubusercontent.com/541093/146456025-28a4e913-0c0e-4f47-aebb-8cd1e03ab818.png">

Filter in workshop header
<img width="983" alt="Screen Shot 2021-12-16 at 5 04 13 PM" src="https://user-images.githubusercontent.com/541093/146456046-150eaa44-3753-41c8-8b7f-3456c2474e50.png">

2021-12-16 22:21 UTC, hlashbrooke requested changes
This looks great! It's exactly what I was hoping to see 😄 

There are three areas where it isn't quite working as expected:

1. The version filter doesn't actually apply on the workshops archive (although it does work on the lesson plans archive) - it updates the URL, but it just shows all the workshops.
2. If a lesson plan has no version tagged, then it still shows "WordPress version" on the lesson plan archive, but there's no data - that needs to be hidden on the archive page if there is no version specified.
3. The version numbers on the single workshop page should link to the filtered archive page for that version. The other meta data items do that and it works correctly on lesson plans, so we need to do it for the WP version on single workshops too.

2021-12-17 18:23 UTC, ryelle commented
> The version filter doesn't actually apply on the workshops archive

😅 it worked before I added it to the lesson plans. Should be working now.

> If a lesson plan has no version tagged, then it still shows "WordPress version" on the lesson plan archive, but there's no data - that needs to be hidden on the archive page if there is no version specified.

The change I just made also hides it on the single lesson plan page, is that OK? or should it say something else on single pages?

> The version numbers on the single workshop page should link to the filtered archive page for that version

Done ✅

2021-12-17 18:52 UTC, hlashbrooke approved these changes

2021-12-17 18:53 UTC, hlashbrooke commented
This all works perfectly now - ready to ship!

2021-12-17 19:09 UTC, merged